package entitats;
// Generated 28-may-2013 11:38:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer id;
     private String titol;
     private String sinopsis;
     private int duracio;
     private String director;
     private int any;
     private String rutaImatge;
     private Boolean tresd;
     private String classificacio;
     private Set generes = new HashSet(0);
     private Set pases = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge) {
        this.titol = titol;
        this.sinopsis = sinopsis;
        this.duracio = duracio;
        this.director = director;
        this.any = any;
        this.rutaImatge = rutaImatge;
    }
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge, Boolean tresd, String classificacio, Set generes, Set pases) {
       this.titol = titol;
       this.sinopsis = sinopsis;
       this.duracio = duracio;
       this.director = director;
       this.any = any;
       this.rutaImatge = rutaImatge;
       this.tresd = tresd;
       this.classificacio = classificacio;
       this.generes = generes;
       this.pases = pases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitol() {
        return this.titol;
    }
    
    public void setTitol(String titol) {
        this.titol = titol;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public int getDuracio() {
        return this.duracio;
    }
    
    public void setDuracio(int duracio) {
        this.duracio = duracio;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public int getAny() {
        return this.any;
    }
    
    public void setAny(int any) {
        this.any = any;
    }
    public String getRutaImatge() {
        return this.rutaImatge;
    }
    
    public void setRutaImatge(String rutaImatge) {
        this.rutaImatge = rutaImatge;
    }
    public Boolean getTresd() {
        return this.tresd;
    }
    
    public void setTresd(Boolean tresd) {
        this.tresd = tresd;
    }
    public String getClassificacio() {
        return this.classificacio;
    }
    
    public void setClassificacio(String classificacio) {
        this.classificacio = classificacio;
    }
    public Set getGeneres() {
        return this.generes;
    }
    
    public void setGeneres(Set generes) {
        this.generes = generes;
    }
    public Set getPases() {
        return this.pases;
    }
    
    public void setPases(Set pases) {
        this.pases = pases;
    }




}


