package entitats;
// Generated 28-may-2013 11:38:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer id;
     private TipusSala tipusSala;
     private String nom;
     private Set pases = new HashSet(0);

    public Sala() {
    }

	
    public Sala(TipusSala tipusSala, String nom) {
        this.tipusSala = tipusSala;
        this.nom = nom;
    }
    public Sala(TipusSala tipusSala, String nom, Set pases) {
       this.tipusSala = tipusSala;
       this.nom = nom;
       this.pases = pases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipusSala getTipusSala() {
        return this.tipusSala;
    }
    
    public void setTipusSala(TipusSala tipusSala) {
        this.tipusSala = tipusSala;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getPases() {
        return this.pases;
    }
    
    public void setPases(Set pases) {
        this.pases = pases;
    }




}


