package entitats;
// Generated 28-may-2013 11:38:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private Float precio;
     private Set entradas = new HashSet(0);

    public Tarifa() {
    }

    public Tarifa(String tipo, Float precio, Set entradas) {
       this.tipo = tipo;
       this.precio = precio;
       this.entradas = entradas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


